baseURL = "http://nilslesieur.fr/"
languageCode = "fr"
title = "nilslesieur.fr"
copyright = "Cette œuvre est mise à disposition selon les termes de la Licence Creative Commons Attribution </br> Pas d’utilisation commerciale - Partage dans les mêmes conditions 4.0 International"
theme = "ananke"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
enableRobotsTXT = true
canonifyURLs = true

[params]
  twitter = "https://twitter.com/nils_back"
  linkedin = "https://www.linkedin.com/in/nilslesieur/"
  description = ""
  
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir"
  background_color_class = "bg-black"
  featured_image = "/images/Paris_BordsDeSeine.jpg"
  
  show_reading_time = true
  recent_post_number = 2 

[Permalinks]
  post = "/:year/:month/:title"
