baseURL = "http://example.org/"
languageCode = "fr"
title = "Le lab de Nils"
theme = "ananke"
DefaultContentLanguage = "fr"

[params]
  twitter = "https://twitter.com/nils_back"

 [Permalinks]
  posts = "posts/:year/:month/:title"