baseURL = "http://nilslesieur.fr/"
languageCode = "fr"
title = "nilslesieur.fr"
theme = "ananke"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 9
enableRobotsTXT = true

[params]
  linkedin = "https://www.linkedin.com/in/nilslesieur/"
	mastodon = "https://piaille.fr/@nils"
  rss = "../index.xml"
  description = ""

  favicon = "/images/favicon.ico"
  
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir"
  background_color_class = "bg-black"
  
  show_reading_time = true
  recent_post_number = 3
  
[Permalinks]
  post = "/:year/:month/:title"
