baseURL = "http://nilslesieur.fr/"
languageCode = "fr"
title = "nilslesieur.fr"
theme = "ananke"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
enableRobotsTXT = true

[params]
  twitter = "https://twitter.com/nils_back"
  linkedin = "https://www.linkedin.com/in/nilslesieur/"
	mastodon = "https://piaille.fr/@nils"
  description = ""

  favicon = "/images/favicon.ico"
  
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir"
  background_color_class = "bg-black"
  featured_image = "/images/Paris_BordsDeSeine.jpg"
  
  show_reading_time = true
  recent_post_number = 2
  
[Permalinks]
  post = "/:year/:month/:title"
